### PR TITLE
Out of order priority frame test

### PR DESCRIPTION
**Pull request by deweerdt**
Add a test to cover the case where a PRIORITY frame is sent for a higher stream id than a subsequent HEADER frame

### CODE REVIEW

**Comment by summerwind** [comment]
Thank you for the PR!
Looks good to me.

**Comment by Scottmitch** [comment]
This actually seems to violate the section 5.1.1 of the RFC. Can you clarify what section(s) of the RFC this test is meant to validate?

https://tools.ietf.org/html/rfc7540#section-5.1.1
> The first use of a new stream identifier implicitly closes all
   streams in the "idle" state that might have been initiated by that
   peer with a lower-valued stream identifier.

**Comment by deweerdt** [comment]
Hello @Scottmitch This is the relevant discussion for H2O: https://github.com/h2o/h2o/pull/1136#issuecomment-266213322.

>    The identifier of a newly established stream MUST be numerically
>    greater than all streams that the initiating endpoint has opened or
>    reserved.  This governs streams that are opened using a HEADERS frame
>    and streams that are reserved using PUSH_PROMISE.  An endpoint that
>    receives an unexpected stream identifier MUST respond with a
>    connection error (Section 5.4.1) of type PROTOCOL_ERROR.

PRIORITY frames don't affect the stream state (receiving it doesn't transition the state from idle to open), PUSH_PROMISE and HEADERS frames do.

**Comment by Scottmitch** [comment]
I agree the terminology `first use of a new stream identifier` and `identifier of a newly established stream` regarding this topic is not crystal clear and could use some clarification. However transitioning stream state and `first use of a stream identifier` are independent concerns that can be enforced simultaneously. Let me open an issue on the HTTP/2 spec and get some more folks to weigh in.

**Pull request merged**
