### PR TITLE
[WIP] Implement h2specd for http2 client testing

### LINKED ISSUE #17: client tests?
As of now, h2spec is only capable of testing servers, acting as a client.  IMO it would be great if h2spec could be run as a server, so that it could be used as a tool to test client implementations.

### PR DESCRIPTION
**Pull request by chhsiao90**
The PR still in an early stage that try to resolve #17 
Just sent the PR for some helpful advise!

### Simply described how h2specd works
The h2specd will start a http server, and will dispatch the request to different handler defined by the test case. Each handler will send different frame and test the client behavior.

After start http server will check the config,
there were two modes depends on arg ```exec``` value

If the ```exec``` had been defined to a specific http2 client binary of script, ex: ```python h2_client.py```
And it will run the http2 client one by one of the test cases like
```
python h2_client.py https://localhost:8443/client/1/1
python h2_client.py https://localhost:8443/client/4.1/1
python h2_client.py https://localhost:8443/client/4.1/2
python h2_client.py https://localhost:8443/client/4.1/3
python h2_client.py https://localhost:8443/client/5/1
```

If the ```exec``` hadn't been set, the browser mode is enabled.
The h2specd will keep running, and you can open browser connect to http(s)://127.0.0.1:port/ and had test on each test case.

### Commands example
```
# client mode
go run cmd/h2spec/h2specd.go -p 8080 -e "python client.py"
# browser mode
go run cmd/h2spec/h2specd.go -t -c /tmp/cert.crt -k /tmp/cert.key -p 8443
```

### Other comment
BTW, duplicate code is somewhere because that I don't want to change exists code so that the PR could be reviewed easier and won't cause code conflict if it would be merged in the future.
And I'm a beginner for golang :)

I had test this with a [hyper-h2](https://github.com/python-hyper/hyper-h2) and I think it works fine!
If need some further information about how to test please let me know.
And any suggestion is welcome, I will appreciate it. Thanks

### CODE REVIEW

**Comment by summerwind** [comment]
Thank you for the PR. Client test support is great!
I'm busy in this week, so I'm going to check this on the weekend.

**Comment by chhsiao90** [comment]
No problem!

**Comment by chhsiao90** [comment]
I had added some more test cases to make sure that the concept works fine.

If need test cases separate into different commit or PR for easily review,
please kindly me know!

**Comment by summerwind** [comment]
I'm still under review. Please wait a little more!

**Comment by chhsiao90** [comment]
No problem, please take your time!

If the concept is fine, I think that will have further work need to be as following.
- How to migrate the new code into current code base, like command line interface, Config, TestCase, etc ...
- How to define the package of test case for server

BTW, the easiest way to test the h2specd, you can use nghttp with following command
```
go run cmd/h2spec/h2specd.go -p 8080 -e nghttp
```

**Comment by summerwind** [comment]
Sorry for the delayed response and thank you for implementing the client test! I like the `exec` option ;) Although there is no big problem overall, I whould like to give some feedback on the concept.

## Command

I agree to separate commands for running client tests. It would be good for me to run the client test with the `h2specd` command like now. Once the client test implementation stabilizes, I'd like to consider integrating with the `h2spec` command in future versions.

## Implementing test cases

I thought it would be good to implement the test case exclusively for the client test. Although some tests may be exactly the same as server tests, duplicate code is not a big problem in the first step. As with commands, I will consider the way to integrate server and client tests in the future.

As you are worried, with the addition of client tests, I think that it would be necessary to change the configuration of the packages. I suggest to place sub packages for server test and client test under the package of each specification as below. Moving an existing test case to the server subpackage is a big change, so could you only add the client subpackage please?


```
/
├── http2/
│   ├── server/
│   │   ├── http2.go
│   │   ├── 1_starting_http2.go
│   │   └── .....
│   └── client/
│       ├── http2.go
│       ├── 1_starting_http2.go
│       └── .....
├── hpack
│   ├── server/
│   │   ├── hpack.go
│   │   ├── 2_3_indexing_tables.go
│   │   └── .....
│   └── client/
│       ├── hpack.go
│       ├── 2_3_indexing_tables.go
│       └── .....
└── generic
    ├── server/
    │   ├── generic.go
    │   ├── 1_starting_http2.go
    │   └── .....
    └── client/
        ├── generic.go
        ├── 1_starting_http2.go
        └── .....
```

## Accessing test cases from client

In the current code, the client specifies the test case by using the path of the URL, but with this method it seems that h2specd can not judge which test case should be executed until receiving the HEADERS frame. Therefore, I think it is difficult to implement test cases related to Connection Preface and SETTINGS frames sent before the HEADERS frame. For example, the following test case seems to be difficult to implement.
https://github.com/summerwind/h2spec/blob/master/http2/3_5_http2_connection_preface.go#L52-L70

I propose a way to divide the port for each test case rather than the URL for this. For example, if you access port 30001, `h2specd` run the test case of http2/3.5/1, and if you access port 30002 `h2specd` will run the test case of http2/3.5/2. It seems good to be able to specify the start number of the port with the command line option.

## Test result of browser mode

The test result in the broser mode is nice! If `h2specd` have an interface that returns a link to the test case or a result in the JSON format, it is convenient because we can run the test automatically with JavaScript on the browser.

## Config package

I recommend that the config package extend the existing `config/config.go` and add necessary methods etc to` h2specd`.

If you have any questions or comments, please feel free to comment on it.
Thank you!

**Comment by chhsiao90** [comment]
@summerwind - Thanks for the review and all the advise are helpful.
Especially about separating the port for each case, that solved some problem that I had encountered.

#### About Command
Yes, I think separate commands will be good, but it seems that golang is not accept same function in same package ( ```def main()``` in ```package main``` )
I'm not familiar with this part, but it might had some solution for that!

#### Implementing test cases
> Moving an existing test case to the server subpackage is a big change, so could you only add the client subpackage please?

Sure, I think I will just keep client tests as is and focus on other stuff.

#### Accessing test cases from client
> I propose a way to divide the port for each test case rather than the URL for this. For example

Cool! That was smart and I will try implement that.

#### Test result of browser mode
After update to port-based test cases, I think automatically test based on javascript may works.
Because when we implement test case based on path, the browser always have just ONE connection to server, we always must wait for previous test result done and the connections closed and we can start doing next test.

#### Config package
> I recommend that the config package extend the existing config/config.go and add necessary methods etc to h2specd.
OK, I will just remove ClientSpecConfig (<= that was a little ugly) and reuse the Config.

**Comment by chhsiao90** [comment]
I addressed the "Config package" with https://github.com/summerwind/h2spec/pull/74/commits/42eb36f8454404969290264451ba3117adede6d2 and "Accessing test cases from client" with https://github.com/summerwind/h2spec/pull/74/commits/6403404ab1679a4effd698f23b13e59c34d367b8 .

Please help review!
Once the review done, I will start working on
- improving browser testing with automatically testing
- improved command line interface (can specific which test to test, like h2spec do)
- Moved http2 handshaking and get first request into the test cases (<= Or maybe this can wait after merged)

Just take your time! and don't be sorry about the lately review, it's fine~

**Comment by summerwind** [comment]
Thank you for the update!
Both of commits are looks good to me, please go ahead.

**Comment by chhsiao90** [comment]
I had enabled browser automatically testing by https://github.com/summerwind/h2spec/pull/74/commits/0d21157c9188e71d3d330910e0f1450c83aa8d49

I used synchronized XMLHttpRequest to invoke those http request call.
And I had added HeaderField("access-control-allow-origin", "*") to CommonRespHeader so that it could bypass same origin policy.

Currently, it seems that only Chrome can run all tests.
Firefox will crash, and Safari will hang with some test case.
I hadn't had a test on Edge.

**Comment by chhsiao90** [comment]
I had figured out why Firefox shutdown and Safari hang.

#### Firefox
It seems that Firefox cannot handle the test case [6_1_data.go#L55-L81](https://github.com/chhsiao90/h2spec/blob/h2specd/client/6_1_data.go#L55-L81) correctly.

#### Safari
Following cases seems will let Safari doing infinite retry and I don't know why.
- [6_5_2_defined_settings_parameters.go#L73-L88](https://github.com/chhsiao90/h2spec/blob/h2specd/client/6_5_2_defined_settings_parameters.go#L73-L88)
- [6_5_3_settings_synchronization.go#L15-L27](https://github.com/chhsiao90/h2spec/blob/h2specd/client/6_5_3_settings_synchronization.go#L15-L27)
- [6_7_ping.go#L16-L25](https://github.com/chhsiao90/h2spec/blob/h2specd/client/6_7_ping.go#L16-L25)
- [6_7_ping.go#L32-L43](https://github.com/chhsiao90/h2spec/blob/h2specd/client/6_7_ping.go#L32-L43)

**Comment by summerwind** [comment]
Thank you for your continued work! 
Automated browser testing is amazing. I reviewed the additional commits and there is no problem with that.

I've also confirmed that Firefox crashes and the behavior of Safari as you said. I don't know why Firefox crashes, but I seems that the reason why Safari doing retry is just resending the HTTP request. 

Using the `-v` option, you can see that Safari is sending HEADERS frames as follows:
```
Generic tests for HTTP/2 client -> 6. Frame Definitions -> 6.5. SETTINGS -> 6.5.2. Defined SETTINGS Parameters
     [send] SETTINGS Frame (length:6, flags:0x00, stream_id:0)
     [send] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
     [recv] WINDOW_UPDATE Frame (length:4, flags:0x00, stream_id:0)
     [recv] HEADERS Frame (length:159, flags:0x05, stream_id:1)
     [send] SETTINGS Frame (length:6, flags:0x00, stream_id:0)
     [send] PING Frame (length:8, flags:0x00, stream_id:0)
     [recv] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
     [recv] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
     [recv] PING Frame (length:8, flags:0x01, stream_id:0)
✔ 4: Sends a SETTINGS frame with unknown identifier
     [send] GOAWAY Frame (length:8, flags:0x00, stream_id:0)
```

This HEADERS frame includes an GET request and is idempotent. So Safari may resend idempotent requests if GOWAY frame returns from server after sending the request. If we use the POST request instead of GET on XHR, then Safari may stop doing retry...

**Comment by chhsiao90** [comment]
For Firefox issue, I had reported a bug report to bugzilla and they would fix that.
For Safari, I think it's not very critical, it still could be done, but will some time to finish.
And IE and Edge, I had test and it seems works fine~

So if there is any need addressed, please let me know, thanks!

**Comment by summerwind** [comment]
Great! 
I will take a look deeper in this weekend...

**Comment by chhsiao90** [comment]
Should I addressed "Moved http2 handshaking and get first request actions into the test cases" in this PR ?
This will be a bit large change that may cause the review harder.
If you are fine with this, I can address it !

**Comment by summerwind** [comment]
Please send me another PR for handshake changes.
The commits in this PR are LTGM. So let's merge.
Thanks you!

**Pull request merged**
