### PR TITLE
Add extra tests for section 6.9.1, when exceeding the flow control window

### PR DESCRIPTION
**Pull request by jthackray**
Hi Moto-san,

I've added a couple more tests, to catch when the flow control window is exceeded
as mentioned in section 6.9.1 of the draft spec.

Kind regards,
Jonathan.

### CODE REVIEW

**Comment by summerwind** [comment]
Thank you for your PR!

Tests for 6.9.1 are looks good to me :)
But the test for 5.5 is no needed I think.

h2spec does not know whether the target server supports extension frames.
If the extension frame (type of 0xFF) means to "Terminate the connection immediately" and the target server supports it, The test case of your PR is always fail.

Thoughts?

**Comment by jthackray** [comment]
Hi,

> But the test for 5.5 is no needed I think.

It was to test this clause:

   "Implementations MUST ignore unknown or unsupported values in all
    extensible protocol elements.  Implementations MUST discard frames
    that have unknown or unsupported types.  This means that any of these
    extension points can be safely used by extensions without prior
    arrangement or negotiation."

> h2spec does not know whether the target server supports extension frames.

All servers should ignore extension frames they don't know
about (i.e. not error), so I was trying to pick a frame value
which isn't yet allocated (0xA is the alt-svc frame type)

> If the extension frame (type of 0xFF) means to "Terminate the connection immediately"
> and the target server supports it, The test case of your PR is always fail.

True. But 0xFF isn't allocated yet. Feel free to drop that test case
if you feel it isn't useful. I've written my own HTTP/2 server, and so
am trying to test it, and h2spec proved very useful, and am now trying
to extend it where it doesn't have tests be should.

Thanks for starting this project! :)

Kind regards,
Jonathan.

**Comment by summerwind** [comment]
Thank you for your comment.
OK, I am going to merge both of 6.9.1 and 5.5 tests.

I will release next version of h2spec on weekend.
Thank you for using h2spec :)

**Comment by jthackray** [comment]
Hi,

> But the test for 5.5 is no needed I think.

 It was to test this clause:

   "Implementations MUST ignore unknown or unsupported values in all
    extensible protocol elements.  Implementations MUST discard frames
    that have unknown or unsupported types.  This means that any of these
    extension points can be safely used by extensions without prior
    arrangement or negotiation."

> h2spec does not know whether the target server supports extension frames.
> If the extension frame (type of 0xFF) means to "Terminate the connection
immediately" and the target server supports it, The test case of your PR is
always fail.

**Pull request merged**
