### PR TITLE
Add negative tests for expected frames in closed state

### PR DESCRIPTION
**Pull request by shane-kearns**
According to RFC7540, these frames should be allowed in the closed
state (to account for race conditions):
RST_STREAM
WINDOW_UPDATE

And the PRIORITY frame is allowed in any state.

### CODE REVIEW

**Comment by summerwind** [comment]
Thank you for your PR!
I'm participating in the HTTP Workshop now.
So I will review your code when I have time

**Comment by summerwind** [comment]
Thank you for your contribution!

Hmm, I don't want to add negative test cases at this time.
Because h2spec is not possible to know that whether the frame is ignored by the target server or not.
I understand that you want, but negative tests may occur more confusion.

I think that there are the following way to add these test cases.

- Receive something like response from the server so that h2spec can judge the results of the test case.
- Add `--negative` option to run the negative test cases. 

thought?

**Comment by shane-kearns** [comment]
If I understand your concern correctly:
Test cases shouldn't wait for a time to expire, but always receive a frame from the server and check it against an expected sequence.

For your first option, do you mean opening a second stream and making a successful HTTP request without seeing any reset frames? (or at least exchange HEADERS)
I don't think we can use a PING frame because of the recommendation to send PING responses before other frames.

I'd prefer not to use --negative because it's better to test all "MUST" items by default.

I'll need to think about this more and revise these test cases.

**Comment by summerwind** [comment]
> If I understand your concern correctly:
> Test cases shouldn't wait for a time to expire, but always receive a frame from the server and check it against an expected sequence.

Yes, your understanding is correct.

> For your first option, do you mean opening a second stream and making a successful HTTP request without seeing any reset frames? (or at least exchange HEADERS)

It depends on the test cases. In the context of this PR, it requires reception of frames that can determine whether RST_STREAM or WINDOW_UPDATE has been ignored.

> I don't think we can use a PING frame because of the recommendation to send PING responses before other frames.
> 
> I'd prefer not to use --negative because it's better to test all "MUST" items by default.

Yes, I totally agree with you.

I'm going to consider more better way... :confused:

**Pull request closed without merging**
